import { Alert, Platform } from 'react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Profile } from '../types';

const escapeHtml = (value: string) =>
  value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

export const buildProfileResumeHtml = (profile: Profile, membership: string) => `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    * { box-sizing: border-box; }
    body {
      font-family: Georgia, 'Times New Roman', serif;
      color: #1A0A2E;
      margin: 0;
      padding: 36px;
      background: #fff;
    }
    .header {
      border-bottom: 3px solid #D4AF37;
      padding-bottom: 18px;
      margin-bottom: 24px;
    }
    .brand {
      color: #2D0B59;
      letter-spacing: 3px;
      font-size: 12px;
      font-weight: 700;
      margin: 0 0 8px;
      text-transform: uppercase;
    }
    h1 {
      margin: 0;
      font-size: 28px;
      color: #2D0B59;
    }
    .subtitle {
      margin-top: 6px;
      color: #6B5B7A;
      font-size: 14px;
    }
    .badge {
      display: inline-block;
      margin-top: 10px;
      padding: 4px 10px;
      border-radius: 999px;
      background: #D4AF37;
      color: #2D0B59;
      font-size: 11px;
      font-weight: 700;
      font-family: Arial, sans-serif;
    }
    h2 {
      margin: 22px 0 8px;
      font-size: 15px;
      color: #D4AF37;
      letter-spacing: 1px;
      text-transform: uppercase;
      border-bottom: 1px solid #E8E0F0;
      padding-bottom: 6px;
      font-family: Arial, sans-serif;
    }
    p {
      margin: 0 0 8px;
      line-height: 1.55;
      font-size: 13px;
      color: #333;
    }
    .grid {
      width: 100%;
      border-collapse: collapse;
    }
    .grid td {
      width: 50%;
      vertical-align: top;
      padding: 4px 12px 4px 0;
      font-size: 13px;
    }
    .label {
      color: #9B8BA8;
      font-size: 11px;
      font-family: Arial, sans-serif;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .value {
      color: #1A0A2E;
      font-weight: 600;
      margin-top: 2px;
    }
    .footer {
      margin-top: 32px;
      padding-top: 12px;
      border-top: 1px solid #E8E0F0;
      font-size: 11px;
      color: #9B8BA8;
      font-family: Arial, sans-serif;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="header">
    <p class="brand">HUMSAFAR · Matrimony Profile Resume</p>
    <h1>${escapeHtml(profile.name)}</h1>
    <div class="subtitle">
      ${profile.age} yrs · ${escapeHtml(profile.height)} · ${escapeHtml(profile.city)}, ${escapeHtml(profile.state)}, ${escapeHtml(profile.country)}
    </div>
    <span class="badge">${escapeHtml(membership)} MEMBER</span>
  </div>

  <h2>Personal Details</h2>
  <table class="grid">
    <tr>
      <td><div class="label">Gender</div><div class="value">${escapeHtml(profile.gender)}</div></td>
      <td><div class="label">Marital Status</div><div class="value">${escapeHtml(profile.maritalStatus)}</div></td>
    </tr>
    <tr>
      <td><div class="label">Sect</div><div class="value">${escapeHtml(profile.sect)}</div></td>
      <td><div class="label">Languages</div><div class="value">${escapeHtml(profile.language)}</div></td>
    </tr>
  </table>

  <h2>About</h2>
  <p>${escapeHtml(profile.about)}</p>

  <h2>Education</h2>
  <p>${escapeHtml(profile.education)}</p>

  <h2>Profession & Income</h2>
  <table class="grid">
    <tr>
      <td><div class="label">Profession</div><div class="value">${escapeHtml(profile.profession)}</div></td>
      <td><div class="label">Income</div><div class="value">${escapeHtml(profile.income)}</div></td>
    </tr>
  </table>

  <h2>Family</h2>
  <p>${escapeHtml(profile.family)}</p>

  <h2>Lifestyle</h2>
  <p>${escapeHtml(profile.lifestyle)}</p>

  <h2>Partner Preference</h2>
  <p>${escapeHtml(profile.partnerPreference)}</p>

  <div class="footer">
    Generated by HUMSAFAR · Find Your Perfect Muslim Life Partner
  </div>
</body>
</html>
`;

const createResumePdf = async (profile: Profile, membership: string) => {
  const html = buildProfileResumeHtml(profile, membership);
  const { uri } = await Print.printToFileAsync({ html });
  return uri;
};

/** Download / save profile details as PDF resume */
export const downloadProfileResume = async (
  profile: Profile,
  membership: string,
) => {
  try {
    if (Platform.OS === 'web') {
      await Print.printAsync({
        html: buildProfileResumeHtml(profile, membership),
      });
      return;
    }

    const uri = await createResumePdf(profile, membership);
    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(uri, {
        mimeType: 'application/pdf',
        dialogTitle: 'Download Profile Resume (PDF)',
        UTI: 'com.adobe.pdf',
      });
    } else {
      Alert.alert('Resume Ready', 'PDF created successfully.');
    }
  } catch (error) {
    Alert.alert('Download Failed', 'Could not create PDF resume. Please try again.');
    console.warn(error);
  }
};

/** Share profile details as PDF resume */
export const shareProfileResume = async (
  profile: Profile,
  membership: string,
) => {
  try {
    if (Platform.OS === 'web') {
      await Print.printAsync({
        html: buildProfileResumeHtml(profile, membership),
      });
      return;
    }

    const uri = await createResumePdf(profile, membership);
    const canShare = await Sharing.isAvailableAsync();
    if (!canShare) {
      Alert.alert('Unavailable', 'Sharing is not available on this device.');
      return;
    }

    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: 'Share Profile Resume (PDF)',
      UTI: 'com.adobe.pdf',
    });
  } catch (error) {
    Alert.alert('Share Failed', 'Could not share PDF resume. Please try again.');
    console.warn(error);
  }
};
